# Generated by Django 4.0.5 on 2022-07-11 08:30

import django.core.validators
from django.db import migrations, models
import djongo.models.fields
import newgame.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameScore',
            fields=[
                ('user_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SingleGameAbstract',
            fields=[
                ('game_score', djongo.models.fields.ArrayField(model_container=newgame.models.GameScore)),
                ('game_name', models.CharField(default='Game number', max_length=30, primary_key=True, serialize=False)),
            ],
            options={
                'managed': False,
            },
        ),
    ]
