# Generated by Django 4.0.5 on 2022-06-17 08:06

from django.db import migrations, models
import django.utils.datetime_safe
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.AutoField(primary_key=True, serialize=False)),
                ('game_name', models.CharField(default='Game number ', max_length=30)),
                ('game_users', djongo.models.fields.JSONField(default={'Kobi': '0', 'Reem': '0', 'Shay': '0'})),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('Tournament_id', models.AutoField(primary_key=True, serialize=False)),
                ('play_date', models.DateField(default=django.utils.datetime_safe.date.today)),
                ('games_score', djongo.models.fields.JSONField(default={'Kobi': '0', 'Reem': '0', 'Shay': '0'})),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=20)),
            ],
        ),
    ]
