# Generated by Django 4.0.5 on 2022-07-10 11:22

from django.db import migrations, models
import django.utils.datetime_safe
import djongo.models.fields
import newgame.models


class Migration(migrations.Migration):

    dependencies = [
        ('newgame', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(default='Game number ', max_length=30)),
                ('game_users', djongo.models.fields.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='TourN',
            fields=[
                ('id', djongo.models.fields.ObjectIdField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('play_date', models.DateField(default=django.utils.datetime_safe.date.today)),
                ('games_list', djongo.models.fields.ArrayField(model_container=newgame.models.SingleGameAbstract, model_form_class=newgame.models.SingleGame)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
            ],
        ),
    ]
